### ISSUE TITLE
Relationship of this project to aws-ddk?

### ISSUE THREAD

**Issue by dashmug** [awslabs/data-solutions-framework-on-aws#460]
How does this project relate to [`aws-ddk`](https://github.com/awslabs/aws-ddk)? If there is alignment in both project's goals, don't you think it is better to merge efforts into a single project that eventually becomes better than both?

**Comment by vgkowski** [comment]
DDK is a great project but I don't think we are sharing the same goals. I see DDK as an abstraction to build data pipelines. It simplifies a lot the pipelines implementation with a composable approach but the result will be a data pipeline.

On the other side, DSF aims to simplify all the layers of data solutions from storage to compute, governance and consumption. We have a strong focus on automating and simplifying the infrastructure and all the tasks you would need to set it up. The result will be a data platform.

At the end, because DSF exposes all the resources that are created, you can still mix DDK and DSF. They can be complementary.
